/*
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import uk.ac.kcl.inf.mde.ide.contentassist.antlr.internal.InternalWeebADoodleParser;
import uk.ac.kcl.inf.mde.services.WeebADoodleGrammarAccess;

public class WeebADoodleParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(WeebADoodleGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, WeebADoodleGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getDirectionAccess().getAlternatives_2(), "rule__Direction__Alternatives_2");
			builder.put(grammarAccess.getStoryboardAccess().getGroup(), "rule__Storyboard__Group__0");
			builder.put(grammarAccess.getSceneAccess().getGroup(), "rule__Scene__Group__0");
			builder.put(grammarAccess.getCharacterAccess().getGroup(), "rule__Character__Group__0");
			builder.put(grammarAccess.getSceneObjectAccess().getGroup(), "rule__SceneObject__Group__0");
			builder.put(grammarAccess.getSettingAccess().getGroup(), "rule__Setting__Group__0");
			builder.put(grammarAccess.getDirectionAccess().getGroup(), "rule__Direction__Group__0");
			builder.put(grammarAccess.getDirectionAccess().getGroup_2_0(), "rule__Direction__Group_2_0__0");
			builder.put(grammarAccess.getDirectionAccess().getGroup_2_1(), "rule__Direction__Group_2_1__0");
			builder.put(grammarAccess.getStoryboardAccess().getScenesAssignment_2(), "rule__Storyboard__ScenesAssignment_2");
			builder.put(grammarAccess.getSceneAccess().getNameAssignment_3(), "rule__Scene__NameAssignment_3");
			builder.put(grammarAccess.getSceneAccess().getValueAssignment_5(), "rule__Scene__ValueAssignment_5");
			builder.put(grammarAccess.getSceneAccess().getBackgroundAssignment_8(), "rule__Scene__BackgroundAssignment_8");
			builder.put(grammarAccess.getSceneAccess().getCharactersAssignment_10(), "rule__Scene__CharactersAssignment_10");
			builder.put(grammarAccess.getSceneAccess().getObjectsAssignment_11(), "rule__Scene__ObjectsAssignment_11");
			builder.put(grammarAccess.getSceneAccess().getSettingsAssignment_12(), "rule__Scene__SettingsAssignment_12");
			builder.put(grammarAccess.getSceneAccess().getDirectionsAssignment_13(), "rule__Scene__DirectionsAssignment_13");
			builder.put(grammarAccess.getCharacterAccess().getNameAssignment_3(), "rule__Character__NameAssignment_3");
			builder.put(grammarAccess.getCharacterAccess().getValueAssignment_5(), "rule__Character__ValueAssignment_5");
			builder.put(grammarAccess.getCharacterAccess().getActionAssignment_8(), "rule__Character__ActionAssignment_8");
			builder.put(grammarAccess.getCharacterAccess().getDialogueAssignment_11(), "rule__Character__DialogueAssignment_11");
			builder.put(grammarAccess.getCharacterAccess().getDescriptionAssignment_14(), "rule__Character__DescriptionAssignment_14");
			builder.put(grammarAccess.getSceneObjectAccess().getNameAssignment_3(), "rule__SceneObject__NameAssignment_3");
			builder.put(grammarAccess.getSceneObjectAccess().getValueAssignment_5(), "rule__SceneObject__ValueAssignment_5");
			builder.put(grammarAccess.getSceneObjectAccess().getPositionAssignment_8(), "rule__SceneObject__PositionAssignment_8");
			builder.put(grammarAccess.getSceneObjectAccess().getDescriptionAssignment_11(), "rule__SceneObject__DescriptionAssignment_11");
			builder.put(grammarAccess.getSettingAccess().getCameraShotAssignment_3(), "rule__Setting__CameraShotAssignment_3");
			builder.put(grammarAccess.getSettingAccess().getCameraAngleAssignment_6(), "rule__Setting__CameraAngleAssignment_6");
			builder.put(grammarAccess.getSettingAccess().getLightingAssignment_9(), "rule__Setting__LightingAssignment_9");
			builder.put(grammarAccess.getSettingAccess().getDescriptionAssignment_12(), "rule__Setting__DescriptionAssignment_12");
			builder.put(grammarAccess.getDirectionAccess().getTargetCharacterAssignment_2_0_1(), "rule__Direction__TargetCharacterAssignment_2_0_1");
			builder.put(grammarAccess.getDirectionAccess().getTargetObjectAssignment_2_1_1(), "rule__Direction__TargetObjectAssignment_2_1_1");
			builder.put(grammarAccess.getDirectionAccess().getMovementAssignment_4(), "rule__Direction__MovementAssignment_4");
			builder.put(grammarAccess.getDirectionAccess().getDescriptionAssignment_6(), "rule__Direction__DescriptionAssignment_6");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private WeebADoodleGrammarAccess grammarAccess;

	@Override
	protected InternalWeebADoodleParser createParser() {
		InternalWeebADoodleParser result = new InternalWeebADoodleParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public WeebADoodleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(WeebADoodleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
