/*
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import uk.ac.kcl.inf.mde.ide.contentassist.antlr.internal.InternalWeebADoodleParser;
import uk.ac.kcl.inf.mde.services.WeebADoodleGrammarAccess;

public class WeebADoodleParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(WeebADoodleGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, WeebADoodleGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getSettingAccess().getAlternatives(), "rule__Setting__Alternatives");
			builder.put(grammarAccess.getActionCommandAccess().getAlternatives(), "rule__ActionCommand__Alternatives");
			builder.put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
			builder.put(grammarAccess.getBoardAccess().getSettingsAssignment(), "rule__Board__SettingsAssignment");
			builder.put(grammarAccess.getActionAccess().getCommandAssignment_0(), "rule__Action__CommandAssignment_0");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private WeebADoodleGrammarAccess grammarAccess;

	@Override
	protected InternalWeebADoodleParser createParser() {
		InternalWeebADoodleParser result = new InternalWeebADoodleParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public WeebADoodleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(WeebADoodleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
