/**
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class WeebADoodleUiModule extends AbstractWeebADoodleUiModule {
  public WeebADoodleUiModule(final AbstractUIPlugin plugin) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe type WeebADoodleUiModule is already defined in WeebADoodleUiModule.java.");
  }
}
