/*
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class WeebADoodleUiModule extends AbstractWeebADoodleUiModule {

	public WeebADoodleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
