/**
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.weebADoodle.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.kcl.inf.mde.weebADoodle.CameraShotStatement;
import uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Camera Shot Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.impl.CameraShotStatementImpl#getCameraShot <em>Camera Shot</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.impl.CameraShotStatementImpl#getCameraAngle <em>Camera Angle</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CameraShotStatementImpl extends MinimalEObjectImpl.Container implements CameraShotStatement
{
  /**
   * The default value of the '{@link #getCameraShot() <em>Camera Shot</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCameraShot()
   * @generated
   * @ordered
   */
  protected static final String CAMERA_SHOT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCameraShot() <em>Camera Shot</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCameraShot()
   * @generated
   * @ordered
   */
  protected String cameraShot = CAMERA_SHOT_EDEFAULT;

  /**
   * The default value of the '{@link #getCameraAngle() <em>Camera Angle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCameraAngle()
   * @generated
   * @ordered
   */
  protected static final String CAMERA_ANGLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCameraAngle() <em>Camera Angle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCameraAngle()
   * @generated
   * @ordered
   */
  protected String cameraAngle = CAMERA_ANGLE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CameraShotStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WeebADoodlePackage.Literals.CAMERA_SHOT_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCameraShot()
  {
    return cameraShot;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCameraShot(String newCameraShot)
  {
    String oldCameraShot = cameraShot;
    cameraShot = newCameraShot;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WeebADoodlePackage.CAMERA_SHOT_STATEMENT__CAMERA_SHOT, oldCameraShot, cameraShot));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCameraAngle()
  {
    return cameraAngle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCameraAngle(String newCameraAngle)
  {
    String oldCameraAngle = cameraAngle;
    cameraAngle = newCameraAngle;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WeebADoodlePackage.CAMERA_SHOT_STATEMENT__CAMERA_ANGLE, oldCameraAngle, cameraAngle));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WeebADoodlePackage.CAMERA_SHOT_STATEMENT__CAMERA_SHOT:
        return getCameraShot();
      case WeebADoodlePackage.CAMERA_SHOT_STATEMENT__CAMERA_ANGLE:
        return getCameraAngle();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WeebADoodlePackage.CAMERA_SHOT_STATEMENT__CAMERA_SHOT:
        setCameraShot((String)newValue);
        return;
      case WeebADoodlePackage.CAMERA_SHOT_STATEMENT__CAMERA_ANGLE:
        setCameraAngle((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WeebADoodlePackage.CAMERA_SHOT_STATEMENT__CAMERA_SHOT:
        setCameraShot(CAMERA_SHOT_EDEFAULT);
        return;
      case WeebADoodlePackage.CAMERA_SHOT_STATEMENT__CAMERA_ANGLE:
        setCameraAngle(CAMERA_ANGLE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WeebADoodlePackage.CAMERA_SHOT_STATEMENT__CAMERA_SHOT:
        return CAMERA_SHOT_EDEFAULT == null ? cameraShot != null : !CAMERA_SHOT_EDEFAULT.equals(cameraShot);
      case WeebADoodlePackage.CAMERA_SHOT_STATEMENT__CAMERA_ANGLE:
        return CAMERA_ANGLE_EDEFAULT == null ? cameraAngle != null : !CAMERA_ANGLE_EDEFAULT.equals(cameraAngle);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (cameraShot: ");
    result.append(cameraShot);
    result.append(", cameraAngle: ");
    result.append(cameraAngle);
    result.append(')');
    return result.toString();
  }

} //CameraShotStatementImpl
