/**
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.weebADoodle.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.kcl.inf.mde.weebADoodle.CameraShotStatement;
import uk.ac.kcl.inf.mde.weebADoodle.DescriptionStatement;
import uk.ac.kcl.inf.mde.weebADoodle.LightingStatement;
import uk.ac.kcl.inf.mde.weebADoodle.Setting;
import uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Setting</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.impl.SettingImpl#getCamera <em>Camera</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.impl.SettingImpl#getLighting <em>Lighting</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.impl.SettingImpl#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SettingImpl extends MinimalEObjectImpl.Container implements Setting
{
  /**
   * The cached value of the '{@link #getCamera() <em>Camera</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCamera()
   * @generated
   * @ordered
   */
  protected CameraShotStatement camera;

  /**
   * The cached value of the '{@link #getLighting() <em>Lighting</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLighting()
   * @generated
   * @ordered
   */
  protected LightingStatement lighting;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected DescriptionStatement description;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SettingImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WeebADoodlePackage.Literals.SETTING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CameraShotStatement getCamera()
  {
    return camera;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCamera(CameraShotStatement newCamera, NotificationChain msgs)
  {
    CameraShotStatement oldCamera = camera;
    camera = newCamera;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WeebADoodlePackage.SETTING__CAMERA, oldCamera, newCamera);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCamera(CameraShotStatement newCamera)
  {
    if (newCamera != camera)
    {
      NotificationChain msgs = null;
      if (camera != null)
        msgs = ((InternalEObject)camera).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WeebADoodlePackage.SETTING__CAMERA, null, msgs);
      if (newCamera != null)
        msgs = ((InternalEObject)newCamera).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WeebADoodlePackage.SETTING__CAMERA, null, msgs);
      msgs = basicSetCamera(newCamera, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WeebADoodlePackage.SETTING__CAMERA, newCamera, newCamera));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LightingStatement getLighting()
  {
    return lighting;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLighting(LightingStatement newLighting, NotificationChain msgs)
  {
    LightingStatement oldLighting = lighting;
    lighting = newLighting;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WeebADoodlePackage.SETTING__LIGHTING, oldLighting, newLighting);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLighting(LightingStatement newLighting)
  {
    if (newLighting != lighting)
    {
      NotificationChain msgs = null;
      if (lighting != null)
        msgs = ((InternalEObject)lighting).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WeebADoodlePackage.SETTING__LIGHTING, null, msgs);
      if (newLighting != null)
        msgs = ((InternalEObject)newLighting).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WeebADoodlePackage.SETTING__LIGHTING, null, msgs);
      msgs = basicSetLighting(newLighting, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WeebADoodlePackage.SETTING__LIGHTING, newLighting, newLighting));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DescriptionStatement getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDescription(DescriptionStatement newDescription, NotificationChain msgs)
  {
    DescriptionStatement oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WeebADoodlePackage.SETTING__DESCRIPTION, oldDescription, newDescription);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(DescriptionStatement newDescription)
  {
    if (newDescription != description)
    {
      NotificationChain msgs = null;
      if (description != null)
        msgs = ((InternalEObject)description).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WeebADoodlePackage.SETTING__DESCRIPTION, null, msgs);
      if (newDescription != null)
        msgs = ((InternalEObject)newDescription).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WeebADoodlePackage.SETTING__DESCRIPTION, null, msgs);
      msgs = basicSetDescription(newDescription, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WeebADoodlePackage.SETTING__DESCRIPTION, newDescription, newDescription));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case WeebADoodlePackage.SETTING__CAMERA:
        return basicSetCamera(null, msgs);
      case WeebADoodlePackage.SETTING__LIGHTING:
        return basicSetLighting(null, msgs);
      case WeebADoodlePackage.SETTING__DESCRIPTION:
        return basicSetDescription(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WeebADoodlePackage.SETTING__CAMERA:
        return getCamera();
      case WeebADoodlePackage.SETTING__LIGHTING:
        return getLighting();
      case WeebADoodlePackage.SETTING__DESCRIPTION:
        return getDescription();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WeebADoodlePackage.SETTING__CAMERA:
        setCamera((CameraShotStatement)newValue);
        return;
      case WeebADoodlePackage.SETTING__LIGHTING:
        setLighting((LightingStatement)newValue);
        return;
      case WeebADoodlePackage.SETTING__DESCRIPTION:
        setDescription((DescriptionStatement)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WeebADoodlePackage.SETTING__CAMERA:
        setCamera((CameraShotStatement)null);
        return;
      case WeebADoodlePackage.SETTING__LIGHTING:
        setLighting((LightingStatement)null);
        return;
      case WeebADoodlePackage.SETTING__DESCRIPTION:
        setDescription((DescriptionStatement)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WeebADoodlePackage.SETTING__CAMERA:
        return camera != null;
      case WeebADoodlePackage.SETTING__LIGHTING:
        return lighting != null;
      case WeebADoodlePackage.SETTING__DESCRIPTION:
        return description != null;
    }
    return super.eIsSet(featureID);
  }

} //SettingImpl
