/**
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.weebADoodle.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import uk.ac.kcl.inf.mde.weebADoodle.ActionStatement;
import uk.ac.kcl.inf.mde.weebADoodle.Board;
import uk.ac.kcl.inf.mde.weebADoodle.CameraShotStatement;
import uk.ac.kcl.inf.mde.weebADoodle.DescriptionStatement;
import uk.ac.kcl.inf.mde.weebADoodle.DialogueStatement;
import uk.ac.kcl.inf.mde.weebADoodle.LightingStatement;
import uk.ac.kcl.inf.mde.weebADoodle.PositionStatement;
import uk.ac.kcl.inf.mde.weebADoodle.Scene;
import uk.ac.kcl.inf.mde.weebADoodle.SceneObject;
import uk.ac.kcl.inf.mde.weebADoodle.Setting;
import uk.ac.kcl.inf.mde.weebADoodle.WeebADoodleFactory;
import uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class WeebADoodleFactoryImpl extends EFactoryImpl implements WeebADoodleFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static WeebADoodleFactory init()
  {
    try
    {
      WeebADoodleFactory theWeebADoodleFactory = (WeebADoodleFactory)EPackage.Registry.INSTANCE.getEFactory(WeebADoodlePackage.eNS_URI);
      if (theWeebADoodleFactory != null)
      {
        return theWeebADoodleFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new WeebADoodleFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WeebADoodleFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case WeebADoodlePackage.BOARD: return createBoard();
      case WeebADoodlePackage.SCENE: return createScene();
      case WeebADoodlePackage.CHARACTER: return createCharacter();
      case WeebADoodlePackage.SCENE_OBJECT: return createSceneObject();
      case WeebADoodlePackage.SETTING: return createSetting();
      case WeebADoodlePackage.DESCRIPTION_STATEMENT: return createDescriptionStatement();
      case WeebADoodlePackage.DIALOGUE_STATEMENT: return createDialogueStatement();
      case WeebADoodlePackage.ACTION_STATEMENT: return createActionStatement();
      case WeebADoodlePackage.POSITION_STATEMENT: return createPositionStatement();
      case WeebADoodlePackage.CAMERA_SHOT_STATEMENT: return createCameraShotStatement();
      case WeebADoodlePackage.LIGHTING_STATEMENT: return createLightingStatement();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Board createBoard()
  {
    BoardImpl board = new BoardImpl();
    return board;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Scene createScene()
  {
    SceneImpl scene = new SceneImpl();
    return scene;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public uk.ac.kcl.inf.mde.weebADoodle.Character createCharacter()
  {
    CharacterImpl character = new CharacterImpl();
    return character;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SceneObject createSceneObject()
  {
    SceneObjectImpl sceneObject = new SceneObjectImpl();
    return sceneObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Setting createSetting()
  {
    SettingImpl setting = new SettingImpl();
    return setting;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DescriptionStatement createDescriptionStatement()
  {
    DescriptionStatementImpl descriptionStatement = new DescriptionStatementImpl();
    return descriptionStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DialogueStatement createDialogueStatement()
  {
    DialogueStatementImpl dialogueStatement = new DialogueStatementImpl();
    return dialogueStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ActionStatement createActionStatement()
  {
    ActionStatementImpl actionStatement = new ActionStatementImpl();
    return actionStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PositionStatement createPositionStatement()
  {
    PositionStatementImpl positionStatement = new PositionStatementImpl();
    return positionStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CameraShotStatement createCameraShotStatement()
  {
    CameraShotStatementImpl cameraShotStatement = new CameraShotStatementImpl();
    return cameraShotStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LightingStatement createLightingStatement()
  {
    LightingStatementImpl lightingStatement = new LightingStatementImpl();
    return lightingStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WeebADoodlePackage getWeebADoodlePackage()
  {
    return (WeebADoodlePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static WeebADoodlePackage getPackage()
  {
    return WeebADoodlePackage.eINSTANCE;
  }

} //WeebADoodleFactoryImpl
