/*
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.inf.mde.WeebADoodleRuntimeModule;
import uk.ac.kcl.inf.mde.WeebADoodleStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class WeebADoodleIdeSetup extends WeebADoodleStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new WeebADoodleRuntimeModule(), new WeebADoodleIdeModule()));
	}
	
}
