/*
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WeebADoodleStandaloneSetup extends WeebADoodleStandaloneSetupGenerated {

	def static void doSetup() {
		new WeebADoodleStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
