/*
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.mde.ui.internal.MdeActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WeebADoodleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MdeActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MdeActivator activator = MdeActivator.getInstance();
		return activator != null ? activator.getInjector(MdeActivator.UK_AC_KCL_INF_MDE_WEEBADOODLE) : null;
	}

}
