/*
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWeebADoodleScopeProvider extends DelegatingScopeProvider {
}
