/**
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.weebADoodle;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Board</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.Board#getScenes <em>Scenes</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getBoard()
 * @model
 * @generated
 */
public interface Board extends EObject
{
  /**
   * Returns the value of the '<em><b>Scenes</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.mde.weebADoodle.Scene}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scenes</em>' containment reference list.
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getBoard_Scenes()
   * @model containment="true"
   * @generated
   */
  EList<Scene> getScenes();

} // Board
