/**
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.weebADoodle;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Camera Shot Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.CameraShotStatement#getCameraShot <em>Camera Shot</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.CameraShotStatement#getCameraAngle <em>Camera Angle</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getCameraShotStatement()
 * @model
 * @generated
 */
public interface CameraShotStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Camera Shot</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Camera Shot</em>' attribute.
   * @see #setCameraShot(String)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getCameraShotStatement_CameraShot()
   * @model
   * @generated
   */
  String getCameraShot();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.CameraShotStatement#getCameraShot <em>Camera Shot</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Camera Shot</em>' attribute.
   * @see #getCameraShot()
   * @generated
   */
  void setCameraShot(String value);

  /**
   * Returns the value of the '<em><b>Camera Angle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Camera Angle</em>' attribute.
   * @see #setCameraAngle(String)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getCameraShotStatement_CameraAngle()
   * @model
   * @generated
   */
  String getCameraAngle();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.CameraShotStatement#getCameraAngle <em>Camera Angle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Camera Angle</em>' attribute.
   * @see #getCameraAngle()
   * @generated
   */
  void setCameraAngle(String value);

} // CameraShotStatement
