/**
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.weebADoodle;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dialogue Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.DialogueStatement#getDialogue <em>Dialogue</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getDialogueStatement()
 * @model
 * @generated
 */
public interface DialogueStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Dialogue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dialogue</em>' attribute.
   * @see #setDialogue(String)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getDialogueStatement_Dialogue()
   * @model
   * @generated
   */
  String getDialogue();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.DialogueStatement#getDialogue <em>Dialogue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dialogue</em>' attribute.
   * @see #getDialogue()
   * @generated
   */
  void setDialogue(String value);

} // DialogueStatement
