/**
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.weebADoodle;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Direction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.Direction#getTargetCharacter <em>Target Character</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.Direction#getTargetObject <em>Target Object</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.Direction#getMovement <em>Movement</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.Direction#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getDirection()
 * @model
 * @generated
 */
public interface Direction extends EObject
{
  /**
   * Returns the value of the '<em><b>Target Character</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Character</em>' reference.
   * @see #setTargetCharacter(uk.ac.kcl.inf.mde.weebADoodle.Character)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getDirection_TargetCharacter()
   * @model
   * @generated
   */
  uk.ac.kcl.inf.mde.weebADoodle.Character getTargetCharacter();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.Direction#getTargetCharacter <em>Target Character</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Character</em>' reference.
   * @see #getTargetCharacter()
   * @generated
   */
  void setTargetCharacter(uk.ac.kcl.inf.mde.weebADoodle.Character value);

  /**
   * Returns the value of the '<em><b>Target Object</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Object</em>' reference.
   * @see #setTargetObject(SceneObject)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getDirection_TargetObject()
   * @model
   * @generated
   */
  SceneObject getTargetObject();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.Direction#getTargetObject <em>Target Object</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Object</em>' reference.
   * @see #getTargetObject()
   * @generated
   */
  void setTargetObject(SceneObject value);

  /**
   * Returns the value of the '<em><b>Movement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Movement</em>' attribute.
   * @see #setMovement(String)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getDirection_Movement()
   * @model
   * @generated
   */
  String getMovement();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.Direction#getMovement <em>Movement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Movement</em>' attribute.
   * @see #getMovement()
   * @generated
   */
  void setMovement(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getDirection_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.Direction#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

} // Direction
