/**
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.weebADoodle;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lighting Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.LightingStatement#getSource <em>Source</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.LightingStatement#getDirection <em>Direction</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getLightingStatement()
 * @model
 * @generated
 */
public interface LightingStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' attribute.
   * @see #setSource(String)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getLightingStatement_Source()
   * @model
   * @generated
   */
  String getSource();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.LightingStatement#getSource <em>Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' attribute.
   * @see #getSource()
   * @generated
   */
  void setSource(String value);

  /**
   * Returns the value of the '<em><b>Direction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direction</em>' attribute.
   * @see #setDirection(String)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getLightingStatement_Direction()
   * @model
   * @generated
   */
  String getDirection();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.LightingStatement#getDirection <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direction</em>' attribute.
   * @see #getDirection()
   * @generated
   */
  void setDirection(String value);

} // LightingStatement
