/**
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.weebADoodle;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scene</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getValue <em>Value</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getBackground <em>Background</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getCharacters <em>Characters</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getObjects <em>Objects</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getSettings <em>Settings</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getDirections <em>Directions</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getScene()
 * @model
 * @generated
 */
public interface Scene extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getScene_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getScene_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Background</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Background</em>' attribute.
   * @see #setBackground(String)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getScene_Background()
   * @model
   * @generated
   */
  String getBackground();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getBackground <em>Background</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Background</em>' attribute.
   * @see #getBackground()
   * @generated
   */
  void setBackground(String value);

  /**
   * Returns the value of the '<em><b>Characters</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.mde.weebADoodle.Character}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Characters</em>' containment reference list.
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getScene_Characters()
   * @model containment="true"
   * @generated
   */
  EList<uk.ac.kcl.inf.mde.weebADoodle.Character> getCharacters();

  /**
   * Returns the value of the '<em><b>Objects</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.mde.weebADoodle.SceneObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objects</em>' containment reference list.
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getScene_Objects()
   * @model containment="true"
   * @generated
   */
  EList<SceneObject> getObjects();

  /**
   * Returns the value of the '<em><b>Settings</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Settings</em>' containment reference.
   * @see #setSettings(Setting)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getScene_Settings()
   * @model containment="true"
   * @generated
   */
  Setting getSettings();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getSettings <em>Settings</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Settings</em>' containment reference.
   * @see #getSettings()
   * @generated
   */
  void setSettings(Setting value);

  /**
   * Returns the value of the '<em><b>Directions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Directions</em>' containment reference.
   * @see #setDirections(Direction)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getScene_Directions()
   * @model containment="true"
   * @generated
   */
  Direction getDirections();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getDirections <em>Directions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Directions</em>' containment reference.
   * @see #getDirections()
   * @generated
   */
  void setDirections(Direction value);

} // Scene
