/**
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.weebADoodle;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Setting</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.Setting#getCamera <em>Camera</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.Setting#getLighting <em>Lighting</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mde.weebADoodle.Setting#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getSetting()
 * @model
 * @generated
 */
public interface Setting extends EObject
{
  /**
   * Returns the value of the '<em><b>Camera</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Camera</em>' containment reference.
   * @see #setCamera(CameraShotStatement)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getSetting_Camera()
   * @model containment="true"
   * @generated
   */
  CameraShotStatement getCamera();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.Setting#getCamera <em>Camera</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Camera</em>' containment reference.
   * @see #getCamera()
   * @generated
   */
  void setCamera(CameraShotStatement value);

  /**
   * Returns the value of the '<em><b>Lighting</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lighting</em>' containment reference.
   * @see #setLighting(LightingStatement)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getSetting_Lighting()
   * @model containment="true"
   * @generated
   */
  LightingStatement getLighting();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.Setting#getLighting <em>Lighting</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lighting</em>' containment reference.
   * @see #getLighting()
   * @generated
   */
  void setLighting(LightingStatement value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' containment reference.
   * @see #setDescription(DescriptionStatement)
   * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage#getSetting_Description()
   * @model containment="true"
   * @generated
   */
  DescriptionStatement getDescription();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mde.weebADoodle.Setting#getDescription <em>Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' containment reference.
   * @see #getDescription()
   * @generated
   */
  void setDescription(DescriptionStatement value);

} // Setting
