/**
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.weebADoodle;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodlePackage
 * @generated
 */
public interface WeebADoodleFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WeebADoodleFactory eINSTANCE = uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodleFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Board</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Board</em>'.
   * @generated
   */
  Board createBoard();

  /**
   * Returns a new object of class '<em>Scene</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Scene</em>'.
   * @generated
   */
  Scene createScene();

  /**
   * Returns a new object of class '<em>Character</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Character</em>'.
   * @generated
   */
  Character createCharacter();

  /**
   * Returns a new object of class '<em>Scene Object</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Scene Object</em>'.
   * @generated
   */
  SceneObject createSceneObject();

  /**
   * Returns a new object of class '<em>Setting</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Setting</em>'.
   * @generated
   */
  Setting createSetting();

  /**
   * Returns a new object of class '<em>Description Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Description Statement</em>'.
   * @generated
   */
  DescriptionStatement createDescriptionStatement();

  /**
   * Returns a new object of class '<em>Dialogue Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dialogue Statement</em>'.
   * @generated
   */
  DialogueStatement createDialogueStatement();

  /**
   * Returns a new object of class '<em>Action Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action Statement</em>'.
   * @generated
   */
  ActionStatement createActionStatement();

  /**
   * Returns a new object of class '<em>Position Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Position Statement</em>'.
   * @generated
   */
  PositionStatement createPositionStatement();

  /**
   * Returns a new object of class '<em>Camera Shot Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Camera Shot Statement</em>'.
   * @generated
   */
  CameraShotStatement createCameraShotStatement();

  /**
   * Returns a new object of class '<em>Lighting Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lighting Statement</em>'.
   * @generated
   */
  LightingStatement createLightingStatement();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  WeebADoodlePackage getWeebADoodlePackage();

} //WeebADoodleFactory
