/**
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.weebADoodle;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.mde.weebADoodle.WeebADoodleFactory
 * @model kind="package"
 * @generated
 */
public interface WeebADoodlePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "weebADoodle";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/mde/WeebADoodle";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "weebADoodle";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WeebADoodlePackage eINSTANCE = uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.BoardImpl <em>Board</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.BoardImpl
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getBoard()
   * @generated
   */
  int BOARD = 0;

  /**
   * The feature id for the '<em><b>Scenes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD__SCENES = 0;

  /**
   * The number of structural features of the '<em>Board</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.SceneImpl <em>Scene</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.SceneImpl
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getScene()
   * @generated
   */
  int SCENE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE__VALUE = 1;

  /**
   * The feature id for the '<em><b>Background</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE__BACKGROUND = 2;

  /**
   * The feature id for the '<em><b>Settings</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE__SETTINGS = 3;

  /**
   * The feature id for the '<em><b>Characters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE__CHARACTERS = 4;

  /**
   * The feature id for the '<em><b>Objects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE__OBJECTS = 5;

  /**
   * The number of structural features of the '<em>Scene</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.CharacterImpl <em>Character</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.CharacterImpl
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getCharacter()
   * @generated
   */
  int CHARACTER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER__VALUE = 1;

  /**
   * The feature id for the '<em><b>Position</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER__POSITION = 2;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER__ACTION = 3;

  /**
   * The feature id for the '<em><b>Dialogue</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER__DIALOGUE = 4;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER__DESCRIPTION = 5;

  /**
   * The number of structural features of the '<em>Character</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.SceneObjectImpl <em>Scene Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.SceneObjectImpl
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getSceneObject()
   * @generated
   */
  int SCENE_OBJECT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE_OBJECT__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE_OBJECT__VALUE = 1;

  /**
   * The feature id for the '<em><b>Position</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE_OBJECT__POSITION = 2;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE_OBJECT__DESCRIPTION = 3;

  /**
   * The number of structural features of the '<em>Scene Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENE_OBJECT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.SettingImpl <em>Setting</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.SettingImpl
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getSetting()
   * @generated
   */
  int SETTING = 4;

  /**
   * The feature id for the '<em><b>Camera</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING__CAMERA = 0;

  /**
   * The feature id for the '<em><b>Lighting</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING__LIGHTING = 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING__DESCRIPTION = 2;

  /**
   * The number of structural features of the '<em>Setting</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.DescriptionStatementImpl <em>Description Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.DescriptionStatementImpl
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getDescriptionStatement()
   * @generated
   */
  int DESCRIPTION_STATEMENT = 5;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION_STATEMENT__DESCRIPTION = 0;

  /**
   * The number of structural features of the '<em>Description Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.DialogueStatementImpl <em>Dialogue Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.DialogueStatementImpl
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getDialogueStatement()
   * @generated
   */
  int DIALOGUE_STATEMENT = 6;

  /**
   * The feature id for the '<em><b>Dialogue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIALOGUE_STATEMENT__DIALOGUE = 0;

  /**
   * The number of structural features of the '<em>Dialogue Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIALOGUE_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.ActionStatementImpl <em>Action Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.ActionStatementImpl
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getActionStatement()
   * @generated
   */
  int ACTION_STATEMENT = 7;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_STATEMENT__ACTION = 0;

  /**
   * The number of structural features of the '<em>Action Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.PositionStatementImpl <em>Position Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.PositionStatementImpl
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getPositionStatement()
   * @generated
   */
  int POSITION_STATEMENT = 8;

  /**
   * The feature id for the '<em><b>Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSITION_STATEMENT__POSITION = 0;

  /**
   * The number of structural features of the '<em>Position Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSITION_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.CameraShotStatementImpl <em>Camera Shot Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.CameraShotStatementImpl
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getCameraShotStatement()
   * @generated
   */
  int CAMERA_SHOT_STATEMENT = 9;

  /**
   * The feature id for the '<em><b>Camera Shot</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_SHOT_STATEMENT__CAMERA_SHOT = 0;

  /**
   * The feature id for the '<em><b>Camera Angle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_SHOT_STATEMENT__CAMERA_ANGLE = 1;

  /**
   * The number of structural features of the '<em>Camera Shot Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_SHOT_STATEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.LightingStatementImpl <em>Lighting Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.LightingStatementImpl
   * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getLightingStatement()
   * @generated
   */
  int LIGHTING_STATEMENT = 10;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGHTING_STATEMENT__SOURCE = 0;

  /**
   * The feature id for the '<em><b>Direction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGHTING_STATEMENT__DIRECTION = 1;

  /**
   * The number of structural features of the '<em>Lighting Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGHTING_STATEMENT_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mde.weebADoodle.Board <em>Board</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Board</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Board
   * @generated
   */
  EClass getBoard();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mde.weebADoodle.Board#getScenes <em>Scenes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Scenes</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Board#getScenes()
   * @see #getBoard()
   * @generated
   */
  EReference getBoard_Scenes();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mde.weebADoodle.Scene <em>Scene</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scene</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Scene
   * @generated
   */
  EClass getScene();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Scene#getName()
   * @see #getScene()
   * @generated
   */
  EAttribute getScene_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Scene#getValue()
   * @see #getScene()
   * @generated
   */
  EAttribute getScene_Value();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getBackground <em>Background</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Background</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Scene#getBackground()
   * @see #getScene()
   * @generated
   */
  EAttribute getScene_Background();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getSettings <em>Settings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Settings</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Scene#getSettings()
   * @see #getScene()
   * @generated
   */
  EReference getScene_Settings();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getCharacters <em>Characters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Characters</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Scene#getCharacters()
   * @see #getScene()
   * @generated
   */
  EReference getScene_Characters();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mde.weebADoodle.Scene#getObjects <em>Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Objects</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Scene#getObjects()
   * @see #getScene()
   * @generated
   */
  EReference getScene_Objects();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mde.weebADoodle.Character <em>Character</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Character</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Character
   * @generated
   */
  EClass getCharacter();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mde.weebADoodle.Character#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Character#getName()
   * @see #getCharacter()
   * @generated
   */
  EAttribute getCharacter_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mde.weebADoodle.Character#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Character#getValue()
   * @see #getCharacter()
   * @generated
   */
  EAttribute getCharacter_Value();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mde.weebADoodle.Character#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Position</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Character#getPosition()
   * @see #getCharacter()
   * @generated
   */
  EReference getCharacter_Position();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mde.weebADoodle.Character#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Action</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Character#getAction()
   * @see #getCharacter()
   * @generated
   */
  EReference getCharacter_Action();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mde.weebADoodle.Character#getDialogue <em>Dialogue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dialogue</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Character#getDialogue()
   * @see #getCharacter()
   * @generated
   */
  EReference getCharacter_Dialogue();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mde.weebADoodle.Character#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Character#getDescription()
   * @see #getCharacter()
   * @generated
   */
  EReference getCharacter_Description();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mde.weebADoodle.SceneObject <em>Scene Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scene Object</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.SceneObject
   * @generated
   */
  EClass getSceneObject();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mde.weebADoodle.SceneObject#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.SceneObject#getName()
   * @see #getSceneObject()
   * @generated
   */
  EAttribute getSceneObject_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mde.weebADoodle.SceneObject#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.SceneObject#getValue()
   * @see #getSceneObject()
   * @generated
   */
  EAttribute getSceneObject_Value();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mde.weebADoodle.SceneObject#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Position</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.SceneObject#getPosition()
   * @see #getSceneObject()
   * @generated
   */
  EReference getSceneObject_Position();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mde.weebADoodle.SceneObject#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.SceneObject#getDescription()
   * @see #getSceneObject()
   * @generated
   */
  EReference getSceneObject_Description();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mde.weebADoodle.Setting <em>Setting</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Setting</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Setting
   * @generated
   */
  EClass getSetting();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mde.weebADoodle.Setting#getCamera <em>Camera</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Camera</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Setting#getCamera()
   * @see #getSetting()
   * @generated
   */
  EReference getSetting_Camera();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mde.weebADoodle.Setting#getLighting <em>Lighting</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lighting</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Setting#getLighting()
   * @see #getSetting()
   * @generated
   */
  EReference getSetting_Lighting();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mde.weebADoodle.Setting#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.Setting#getDescription()
   * @see #getSetting()
   * @generated
   */
  EReference getSetting_Description();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mde.weebADoodle.DescriptionStatement <em>Description Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Description Statement</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.DescriptionStatement
   * @generated
   */
  EClass getDescriptionStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mde.weebADoodle.DescriptionStatement#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.DescriptionStatement#getDescription()
   * @see #getDescriptionStatement()
   * @generated
   */
  EAttribute getDescriptionStatement_Description();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mde.weebADoodle.DialogueStatement <em>Dialogue Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dialogue Statement</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.DialogueStatement
   * @generated
   */
  EClass getDialogueStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mde.weebADoodle.DialogueStatement#getDialogue <em>Dialogue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dialogue</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.DialogueStatement#getDialogue()
   * @see #getDialogueStatement()
   * @generated
   */
  EAttribute getDialogueStatement_Dialogue();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mde.weebADoodle.ActionStatement <em>Action Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action Statement</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.ActionStatement
   * @generated
   */
  EClass getActionStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mde.weebADoodle.ActionStatement#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.ActionStatement#getAction()
   * @see #getActionStatement()
   * @generated
   */
  EAttribute getActionStatement_Action();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mde.weebADoodle.PositionStatement <em>Position Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Position Statement</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.PositionStatement
   * @generated
   */
  EClass getPositionStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mde.weebADoodle.PositionStatement#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Position</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.PositionStatement#getPosition()
   * @see #getPositionStatement()
   * @generated
   */
  EAttribute getPositionStatement_Position();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mde.weebADoodle.CameraShotStatement <em>Camera Shot Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Camera Shot Statement</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.CameraShotStatement
   * @generated
   */
  EClass getCameraShotStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mde.weebADoodle.CameraShotStatement#getCameraShot <em>Camera Shot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Camera Shot</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.CameraShotStatement#getCameraShot()
   * @see #getCameraShotStatement()
   * @generated
   */
  EAttribute getCameraShotStatement_CameraShot();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mde.weebADoodle.CameraShotStatement#getCameraAngle <em>Camera Angle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Camera Angle</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.CameraShotStatement#getCameraAngle()
   * @see #getCameraShotStatement()
   * @generated
   */
  EAttribute getCameraShotStatement_CameraAngle();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mde.weebADoodle.LightingStatement <em>Lighting Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lighting Statement</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.LightingStatement
   * @generated
   */
  EClass getLightingStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mde.weebADoodle.LightingStatement#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.LightingStatement#getSource()
   * @see #getLightingStatement()
   * @generated
   */
  EAttribute getLightingStatement_Source();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mde.weebADoodle.LightingStatement#getDirection <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Direction</em>'.
   * @see uk.ac.kcl.inf.mde.weebADoodle.LightingStatement#getDirection()
   * @see #getLightingStatement()
   * @generated
   */
  EAttribute getLightingStatement_Direction();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  WeebADoodleFactory getWeebADoodleFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.BoardImpl <em>Board</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.BoardImpl
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getBoard()
     * @generated
     */
    EClass BOARD = eINSTANCE.getBoard();

    /**
     * The meta object literal for the '<em><b>Scenes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOARD__SCENES = eINSTANCE.getBoard_Scenes();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.SceneImpl <em>Scene</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.SceneImpl
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getScene()
     * @generated
     */
    EClass SCENE = eINSTANCE.getScene();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCENE__NAME = eINSTANCE.getScene_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCENE__VALUE = eINSTANCE.getScene_Value();

    /**
     * The meta object literal for the '<em><b>Background</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCENE__BACKGROUND = eINSTANCE.getScene_Background();

    /**
     * The meta object literal for the '<em><b>Settings</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENE__SETTINGS = eINSTANCE.getScene_Settings();

    /**
     * The meta object literal for the '<em><b>Characters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENE__CHARACTERS = eINSTANCE.getScene_Characters();

    /**
     * The meta object literal for the '<em><b>Objects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENE__OBJECTS = eINSTANCE.getScene_Objects();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.CharacterImpl <em>Character</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.CharacterImpl
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getCharacter()
     * @generated
     */
    EClass CHARACTER = eINSTANCE.getCharacter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHARACTER__NAME = eINSTANCE.getCharacter_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHARACTER__VALUE = eINSTANCE.getCharacter_Value();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHARACTER__POSITION = eINSTANCE.getCharacter_Position();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHARACTER__ACTION = eINSTANCE.getCharacter_Action();

    /**
     * The meta object literal for the '<em><b>Dialogue</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHARACTER__DIALOGUE = eINSTANCE.getCharacter_Dialogue();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHARACTER__DESCRIPTION = eINSTANCE.getCharacter_Description();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.SceneObjectImpl <em>Scene Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.SceneObjectImpl
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getSceneObject()
     * @generated
     */
    EClass SCENE_OBJECT = eINSTANCE.getSceneObject();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCENE_OBJECT__NAME = eINSTANCE.getSceneObject_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCENE_OBJECT__VALUE = eINSTANCE.getSceneObject_Value();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENE_OBJECT__POSITION = eINSTANCE.getSceneObject_Position();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENE_OBJECT__DESCRIPTION = eINSTANCE.getSceneObject_Description();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.SettingImpl <em>Setting</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.SettingImpl
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getSetting()
     * @generated
     */
    EClass SETTING = eINSTANCE.getSetting();

    /**
     * The meta object literal for the '<em><b>Camera</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SETTING__CAMERA = eINSTANCE.getSetting_Camera();

    /**
     * The meta object literal for the '<em><b>Lighting</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SETTING__LIGHTING = eINSTANCE.getSetting_Lighting();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SETTING__DESCRIPTION = eINSTANCE.getSetting_Description();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.DescriptionStatementImpl <em>Description Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.DescriptionStatementImpl
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getDescriptionStatement()
     * @generated
     */
    EClass DESCRIPTION_STATEMENT = eINSTANCE.getDescriptionStatement();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESCRIPTION_STATEMENT__DESCRIPTION = eINSTANCE.getDescriptionStatement_Description();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.DialogueStatementImpl <em>Dialogue Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.DialogueStatementImpl
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getDialogueStatement()
     * @generated
     */
    EClass DIALOGUE_STATEMENT = eINSTANCE.getDialogueStatement();

    /**
     * The meta object literal for the '<em><b>Dialogue</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIALOGUE_STATEMENT__DIALOGUE = eINSTANCE.getDialogueStatement_Dialogue();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.ActionStatementImpl <em>Action Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.ActionStatementImpl
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getActionStatement()
     * @generated
     */
    EClass ACTION_STATEMENT = eINSTANCE.getActionStatement();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION_STATEMENT__ACTION = eINSTANCE.getActionStatement_Action();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.PositionStatementImpl <em>Position Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.PositionStatementImpl
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getPositionStatement()
     * @generated
     */
    EClass POSITION_STATEMENT = eINSTANCE.getPositionStatement();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POSITION_STATEMENT__POSITION = eINSTANCE.getPositionStatement_Position();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.CameraShotStatementImpl <em>Camera Shot Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.CameraShotStatementImpl
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getCameraShotStatement()
     * @generated
     */
    EClass CAMERA_SHOT_STATEMENT = eINSTANCE.getCameraShotStatement();

    /**
     * The meta object literal for the '<em><b>Camera Shot</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAMERA_SHOT_STATEMENT__CAMERA_SHOT = eINSTANCE.getCameraShotStatement_CameraShot();

    /**
     * The meta object literal for the '<em><b>Camera Angle</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAMERA_SHOT_STATEMENT__CAMERA_ANGLE = eINSTANCE.getCameraShotStatement_CameraAngle();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mde.weebADoodle.impl.LightingStatementImpl <em>Lighting Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.LightingStatementImpl
     * @see uk.ac.kcl.inf.mde.weebADoodle.impl.WeebADoodlePackageImpl#getLightingStatement()
     * @generated
     */
    EClass LIGHTING_STATEMENT = eINSTANCE.getLightingStatement();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIGHTING_STATEMENT__SOURCE = eINSTANCE.getLightingStatement_Source();

    /**
     * The meta object literal for the '<em><b>Direction</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIGHTING_STATEMENT__DIRECTION = eINSTANCE.getLightingStatement_Direction();

  }

} //WeebADoodlePackage
