/**
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class WeebADoodleStandaloneSetup extends WeebADoodleStandaloneSetupGenerated {
  public static void doSetup() {
    new WeebADoodleStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
