/*
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.mde.ui.internal.MdeActivator;

public class WeebADoodleUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MdeActivator.getInstance().getInjector("uk.ac.kcl.inf.mde.WeebADoodle");
	}

}
