/**
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.ui.quickfix;

import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import uk.ac.kcl.inf.mde.validation.WeebADoodleValidator;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class WeebADoodleQuickfixProvider extends DefaultQuickfixProvider {
  @Fix(WeebADoodleValidator.INVALID_NAME)
  public void renameCharacter(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final IModification _function = (IModificationContext element) -> {
      final uk.ac.kcl.inf.mde.weebADoodle.Character character = ((uk.ac.kcl.inf.mde.weebADoodle.Character) element);
      character.setName("NewName");
      character.setName("Rufus");
    };
    acceptor.accept(issue, "Rename character to a longer name", "Replace the character name with a new, longer name.", null, _function);
  }
}
