/*
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mde.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WeebADoodleAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("uk/ac/kcl/inf/mde/parser/antlr/internal/InternalWeebADoodle.tokens");
	}
}
